### ISSUE TITLE
写的不错

### ISSUE THREAD

**Issue by scsfwgy** [OliverY/RxjavaYxj#1]
之前跟过几次Rxjava的代码，很容易跟丢。最主要的原因是各种其它因素干扰，各种判断。另外一个原因就是内部接口各种变化和持有。
很不错的想法实践，剥离出核心接口演绎过程。

**Comment by OliverY** [comment]
非常感谢哈

看了挺久的Rxjava源码和分析文章，都感觉不容易懂，经常看到一点就忘记了前面的（读源码的通病吧）。

然后又觉得Rxjava怎么能这样干，很神奇。后来终于想明白大概是怎么回事，决定自己简写一个试试。
